version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lights:
    build: .
    command: yarn dev
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=*.lights.localhost
    volumes:
      - .:/usr/src/app
